/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

#define BV(n) (1 << (n))

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void led_init(void);
void led_on(void);
void led_off(void);
void led_blink_all(void);

int main(void)
{
    led_init();

    while (1)
    {
        led_blink_all();   // All LEDs blink together
    }
}


void led_init(void)
{
    /* Enable clock for GPIOD */
    RCC->AHB1ENR |= BV(3);

    /* Configure PD12–PD15 as output */
    GPIOD->MODER &= ~(BV(25) | BV(27) | BV(29) | BV(31));
    GPIOD->MODER |=  (BV(24) | BV(26) | BV(28) | BV(30));

    /* Push-pull output */
    GPIOD->OTYPER &= ~(BV(12) | BV(13) | BV(14) | BV(15));

    /* Low speed */
    GPIOD->OSPEEDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) |
                        BV(28) | BV(29) | BV(30) | BV(31));

    /* No pull-up, pull-down */
    GPIOD->PUPDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) |
                      BV(28) | BV(29) | BV(30) | BV(31));
}

/* Turn ON all LEDs */
void led_on(void)
{
    GPIOD->ODR |= (BV(12) | BV(13) | BV(14) | BV(15));
}

/* Turn OFF all LEDs */
void led_off(void)
{
    GPIOD->ODR &= ~(BV(12) | BV(13) | BV(14) | BV(15));
}

/* All LEDs Blink Together */
void led_blink_all(void)
{
    led_on();          // LEDs ON
    DelayMs(300);      // 300 ms delay

    led_off();         // LEDs OFF
    DelayMs(300);      // 300 ms delay
}
